#!/bin/bash

# TuxPulse v6.0 Unified Builder Script
# This script generates .deb, .rpm, .flatpak (manifest), and .pkg.tar.zst packages.

echo "--- TuxPulse v6.0 Unified Build Process ---"

# 1. Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "[1/5] Installing Node.js dependencies..."
    npm install
fi

# 2. Build the frontend
echo "[2/5] Building frontend assets..."
npm run build

# 3. Build native packages with Tauri
echo "[3/5] Building native packages (DEB, RPM)..."
# Tauri v2 build command
npm run tauri build

# 4. Generate Arch Linux package (.pkg.tar.zst)
echo "[4/5] Generating Arch Linux package (.pkg.tar.zst)..."
VERSION=$(grep '^version =' src-tauri/Cargo.toml | head -n 1 | cut -d '"' -f 2)
BUILD_DIR="dist/arch_build"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/usr/bin"
mkdir -p "$BUILD_DIR/usr/share/applications"
mkdir -p "$BUILD_DIR/usr/share/polkit-1/actions"
mkdir -p "$BUILD_DIR/usr/share/icons/hicolor/512x512/apps"

# Copy binary
cp src-tauri/target/release/tuxpulse "$BUILD_DIR/usr/bin/"

# Copy system files
[ -f "system_files/tuxpulse.desktop" ] && cp system_files/tuxpulse.desktop "$BUILD_DIR/usr/share/applications/"
[ -f "system_files/com.eoliann.tuxpulse.policy" ] && cp system_files/com.eoliann.tuxpulse.policy "$BUILD_DIR/usr/share/polkit-1/actions/"
[ -f "src-tauri/icons/128x128.png" ] && cp src-tauri/icons/128x128.png "$BUILD_DIR/usr/share/icons/hicolor/512x512/apps/tuxpulse.png"

# Create .PKGINFO (Strict Arch format: no spaces around =, pkgver includes pkgrel)
# This is the format generated by makepkg
cat > "$BUILD_DIR/.PKGINFO" <<EOF
pkgname=tuxpulse
pkgver=${VERSION}-1
pkgdesc=Secure System Monitoring and Management Toolkit
url=https://github.com/eoliann/tuxpulse
builddate=$(date +%s)
packager=TuxPulse Builder
size=$(du -sb "$BUILD_DIR/usr" | cut -f1)
arch=x86_64
license=GPL3
depend=openssl
depend=gtk3
depend=libappindicator-gtk3
EOF

# Compress to .pkg.tar.zst
# CRITICAL: .PKGINFO must be at the root, and we must NOT have a leading ./ in the archive
cd "$BUILD_DIR"
if command -v zstd &> /dev/null; then
    # Use --no-recursion to be safe or just list files
    tar --zstd -cf "../tuxpulse-${VERSION}-x86_64.pkg.tar.zst" .PKGINFO usr
else
    tar -czf "../tuxpulse-${VERSION}-x86_64.pkg.tar.gz" .PKGINFO usr
    echo "Warning: zstd not found, created .tar.gz instead."
fi
cd ../..

# 5. Flatpak (Placeholder - requires flatpak-builder and manifest)
echo "[5/5] Flatpak generation requires flatpak-builder."
echo "Please use the provided flatpak manifest in system_files/flatpak/"

# Summary
echo "--- Build complete! ---"
echo "Packages generated in:"
echo " - DEB: src-tauri/target/release/bundle/deb/"
echo " - RPM: src-tauri/target/release/bundle/rpm/"
echo " - Arch: dist/tuxpulse-${VERSION}-x86_64.pkg.tar.zst (or .gz)"
