#!/usr/bin/env node
import { access, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const checkOnly = process.argv.includes('--check');

const files = {
  packageJson: path.join(rootDir, 'package.json'),
  packageLock: path.join(rootDir, 'package-lock.json'),
  tauriConfig: path.join(rootDir, 'src-tauri', 'tauri.conf.json'),
  cargoToml: path.join(rootDir, 'src-tauri', 'Cargo.toml'),
  versionTs: path.join(rootDir, 'src', 'version.ts'),
};

const SEMVER_RE = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

async function exists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readJson(filePath) {
  return JSON.parse(await readFile(filePath, 'utf8'));
}

async function writeIfChanged(filePath, nextContent) {
  let previousContent = null;
  try {
    previousContent = await readFile(filePath, 'utf8');
  } catch {
    previousContent = null;
  }

  if (previousContent === nextContent) {
    return false;
  }

  if (checkOnly) {
    throw new Error(`Version is not synchronized in ${path.relative(rootDir, filePath)}`);
  }

  await writeFile(filePath, nextContent);
  return true;
}

function updateTomlPackageVersion(content, version) {
  const packageSectionMatch = content.match(/(^\[package\][\s\S]*?)(?=\n\[|\s*$)/);
  if (!packageSectionMatch) {
    throw new Error('Could not find [package] section in src-tauri/Cargo.toml');
  }

  const packageSection = packageSectionMatch[1];
  if (!/^version\s*=\s*"[^"]+"/m.test(packageSection)) {
    throw new Error('Could not find package version in src-tauri/Cargo.toml');
  }

  const updatedPackageSection = packageSection.replace(
    /^version\s*=\s*"[^"]+"/m,
    `version = "${version}"`,
  );

  return content.replace(packageSection, updatedPackageSection);
}

function versionTsContent(version) {
  return `// This file is generated by scripts/sync-version.mjs.\n// Do not edit this version manually. Change package.json instead.\n\nexport const APP_VERSION_RAW = '${version}';\nexport const APP_VERSION = 'v${version}';\n`;
}

async function main() {
  const packageJson = await readJson(files.packageJson);
  const version = packageJson.version;

  if (!version || !SEMVER_RE.test(version)) {
    throw new Error(`Invalid package.json version: ${version}`);
  }

  const changed = [];

  const tauriConfig = await readJson(files.tauriConfig);
  tauriConfig.version = version;
  if (await writeIfChanged(files.tauriConfig, `${JSON.stringify(tauriConfig, null, 2)}\n`)) {
    changed.push('src-tauri/tauri.conf.json');
  }

  const cargoToml = await readFile(files.cargoToml, 'utf8');
  const nextCargoToml = updateTomlPackageVersion(cargoToml, version);
  if (await writeIfChanged(files.cargoToml, nextCargoToml)) {
    changed.push('src-tauri/Cargo.toml');
  }

  if (await writeIfChanged(files.versionTs, versionTsContent(version))) {
    changed.push('src/version.ts');
  }

  if (await exists(files.packageLock)) {
    const packageLock = await readJson(files.packageLock);
    packageLock.version = version;
    if (packageLock.packages?.['']) {
      packageLock.packages[''].version = version;
    }
    if (await writeIfChanged(files.packageLock, `${JSON.stringify(packageLock, null, 2)}\n`)) {
      changed.push('package-lock.json');
    }
  }

  if (checkOnly) {
    console.log(`Version synchronization OK: ${version}`);
    return;
  }

  if (changed.length === 0) {
    console.log(`Version already synchronized: ${version}`);
  } else {
    console.log(`Version synchronized to ${version}:`);
    for (const fileName of changed) {
      console.log(`- ${fileName}`);
    }
  }
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
