// This file is generated by scripts/sync-version.mjs.
// Do not edit this version manually. Change package.json instead.

export const APP_VERSION_RAW = '6.0.7';
export const APP_VERSION = 'v6.0.7';
